### ISSUE TITLE
Parameter extraction failed, No useful data returned

### ISSUE THREAD

**Issue by maximmax-crypto** [melexis/mlx90640-library#103]
Hi. 

I have the same issue as already asked: https://github.com/melexis/mlx90640-library/issues/13. For communication the STM32F407G is used. I have the ability to give you the needet data, so we can try to solve the problem together. The Function DumpEE returns 0, so i think the communication is astablished.  
After ExtractParameters i have the followind Parameters calculated: 
![Screenshot 2023-04-13 135841](https://user-images.githubusercontent.com/130676795/231789557-4efca9cd-7d73-4277-ba64-1b0b8becd075.png)

Are the ExtractParameter incorrect?

**Comment by slavysis** [comment]
Hi, as a first step, could you please share the EEPROM dump data.

**Comment by maximmax-crypto** [comment]
I cant sent you all the Data. But here a couple examples: 
![Screenshot 2023-04-19 143305](https://user-images.githubusercontent.com/130676795/233076403-b7fc70d9-6f4f-4cd3-a599-e5128eaa4cc5.png)
![Screenshot 2023-04-19 143104](https://user-images.githubusercontent.com/130676795/233076412-695759ff-aaef-4dbc-9d94-524bff6fab59.png)

**Comment by maximmax-crypto** [comment]
I cant send you all 834 Words. But here some examples:

![Screenshot 2023-04-19 143104](https://user-images.githubusercontent.com/130676795/233076831-7eadc2dc-5f6d-4bf9-aea8-75adc342038c.png)
![Screenshot 2023-04-19 143305](https://user-images.githubusercontent.com/130676795/233076840-29d011f4-dd9b-41fd-ab2b-3391d7532c95.png)

Do you want somethink specifik?

**Comment by slavysis** [comment]
Some of those values indeed look strange, Based on the EEPROM data you sent, I would say that this is a MLX90641 device that you are using (not MLX90640). Can you please check the marking to make sure what device you have.

P.S. You can log the full data in a csv file and attach it. It would be much easier than series of pictures

**Comment by maximmax-crypto** [comment]
Thanks for your support. You are right. I was using the wrong sensor.
