### ISSUE TITLE
MLX90640 Parameter Check - MLX90640_BROKEN_PIXELS_NUM_ERROR

### ISSUE THREAD

**Issue by ryanlederhose** [melexis/mlx90640-library#107]
When checking the parameters initially I get a MLX90640_BROKEN_PIXELS_NUM_ERROR. Through debugging I found the brokenPixCnt=4 in the ExtractDeviatingPixels function. I am using the Teensy 4.1 and I have also attached a dump of EEPROM dump:

![image](https://github.com/melexis/mlx90640-library/assets/112144274/1b261c1c-2833-4939-b7af-943c2d2480cd)

Any ideas on how to fix this?

Thanks

**Comment by slavysis** [comment]
Is it possible to give the EEPROM dump in a format that would allow to easily work with it? Extracting over 800 values from a picture is a bit too inconvenient.

**Comment by ryanlederhose** [comment]
Of course. Thanks for the reply. Might this be easier?

eeMLX90640 Array:
Index 0  194
Index 1  31135
Index 2  0
Index 3  8289
Index 4  5
Index 5  800
Index 6  992
Index 7  2346
Index 8  46834
Index 9  393
Index 10  1177
Index 11  0
Index 12  0
Index 13  0
Index 14  0
Index 15  48691
Index 16  17184
Index 17  65465
Index 18  257
Index 19  257
Index 20  257
Index 21  61937
Index 22  57585
Index 23  53200
Index 24  0
Index 25  1
Index 26  2
Index 27  61698
Index 28  61698
Index 29  61698
Index 30  57586
Index 31  49377
Index 32  35221
Index 33  14850
Index 34  61148
Index 35  4111
Index 36  4369
Index 37  4386
Index 38  273
Index 39  65280
Index 40  0
Index 41  15
Index 42  8738
Index 43  13107
Index 44  8755
Index 45  4386
Index 46  60928
Index 47  43997
Index 48  6197
Index 49  12201
Index 50  8535
Index 51  42369
Index 52  30294
Index 53  63940
Index 54  13877
Index 55  13105
Index 56  9298
Index 57  3193
Index 58  6067
Index 59  1573
Index 60  62976
Index 61  38807
Index 62  38807
Index 63  11002
Index 64  9152
Index 65  4304
Index 66  8398
Index 67  1998
Index 68  0
Index 69  6048
Index 70  10350
Index 71  64702
Index 72  1086
Index 73  5104
Index 74  10414
Index 75  64590
Index 76  174
Index 77  2128
Index 78  5294
Index 79  1086
Index 80  4224
Index 81  1104
Index 82  6302
Index 83  64718
Index 84  1214
Index 85  928
Index 86  3278
Index 87  63422
Index 88  2144
Index 89  63536
Index 90  6304
Index 91  61518
Index 92  46
Index 93  63456
Index 94  6082
Index 95  62448
Index 96  0
Index 97  3120
Index 98  64540
Index 99  7952
Index 100  6112
Index 101  4848
Index 102  1996
Index 103  6176
Index 104  1936
Index 105  3934
Index 106  1036
Index 107  6048
Index 108  16
Index 109  2992
Index 110  62478
Index 111  8096
Index 112  7156
Index 113  2000
Index 114  65534
Index 115  5168
Index 116  3122
Index 117  768
Index 118  61500
Index 119  4944
Index 120  5074
Index 121  65424
Index 122  1054
Index 123  5056
Index 124  0
Index 125  65344
Index 126  65358
Index 127  4992
Index 128  7968
Index 129  6096
Index 130  7246
Index 131  846
Index 132  2174
Index 133  4016
Index 134  8286
Index 135  64590
Index 136  2848
Index 137  5008
Index 138  12160
Index 139  65518
Index 140  2032
Index 141  2080
Index 142  6110
Index 143  14
Index 144  4130
Index 145  1008
Index 146  6206
Index 147  63598
Index 148  1168
Index 149  64512
Index 150  6112
Index 151  62320
Index 152  0
Index 153  65456
Index 154  7248
Index 155  63454
Index 156  2992
Index 157  65344
Index 158  7040
Index 159  62416
Index 160  9090
Index 161  3136
Index 162  64668
Index 163  7072
Index 164  3264
Index 165  3088
Index 166  204
Index 167  5280
Index 168  3970
Index 169  4080
Index 170  4062
Index 171  5184
Index 172  2130
Index 173  1136
Index 174  63534
Index 175  6224
Index 176  5220
Index 177  1088
Index 178  64654
Index 179  5312
Index 180  0
Index 181  64608
Index 182  63566
Index 183  5088
Index 184  3266
Index 185  32
Index 186  1214
Index 187  4176
Index 188  4114
Index 189  944
Index 190  64526
Index 191  3152
Index 192  9136
Index 193  5136
Index 194  8286
Index 195  1918
Index 196  6240
Index 197  6032
Index 198  8398
Index 199  64686
Index 200  5056
Index 201  4096
Index 202  9310
Index 203  63598
Index 204  3104
Index 205  2208
Index 206  7056
Index 207  64670
Index 208  0
Index 209  1088
Index 210  4398
Index 211  64686
Index 212  3154
Index 213  63632
Index 214  5216
Index 215  63472
Index 216  2178
Index 217  2
Index 218  7328
Index 219  62510
Index 220  1120
Index 221  960
Index 222  7088
Index 223  62464
Index 224  7938
Index 225  2928
Index 226  64446
Index 227  4816
Index 228  5072
Index 229  3792
Index 230  64540
Index 231  4112
Index 232  3874
Index 233  2912
Index 234  1934
Index 235  4000
Index 236  0
Index 237  992
Index 238  64238
Index 239  6096
Index 240  6948
Index 241  65408
Index 242  61550
Index 243  6112
Index 244  5012
Index 245  64464
Index 246  63406
Index 247  3920
Index 248  4082
Index 249  864
Index 250  14
Index 251  4992
Index 252  3010
Index 253  816
Index 254  65294
Index 255  3952
Index 256  5088
Index 257  4242
Index 258  7310
Index 259  992
Index 260  2270
Index 261  6080
Index 262  9390
Index 263  64814
Index 264  0
Index 265  3136
Index 266  9390
Index 267  63566
Index 268  3040
Index 269  2146
Index 270  6128
Index 271  2014
Index 272  3106
Index 273  80
Index 274  4336
Index 275  63648
Index 276  2114
Index 277  64544
Index 278  4176
Index 279  60528
Index 280  1248
Index 281  16
Index 282  8304
Index 283  62528
Index 284  2064
Index 285  1952
Index 286  7136
Index 287  62528
Index 288  2866
Index 289  65488
Index 290  62430
Index 291  2864
Index 292  32
Index 293  0
Index 294  64462
Index 295  2144
Index 296  786
Index 297  65408
Index 298  64494
Index 299  2944
Index 300  802
Index 301  65440
Index 302  61230
Index 303  6912
Index 304  3908
Index 305  64384
Index 306  60462
Index 307  4048
Index 308  2932
Index 309  63312
Index 310  61326
Index 311  1968
Index 312  1074
Index 313  832
Index 314  974
Index 315  2976
Index 316  3906
Index 317  736
Index 318  64302
Index 319  2976
Index 320  5936
Index 321  0
Index 322  7168
Index 323  65424
Index 324  2192
Index 325  5056
Index 326  8240
Index 327  64592
Index 328  912
Index 329  4002
Index 330  9198
Index 331  62526
Index 332  1008
Index 333  2082
Index 334  5056
Index 335  878
Index 336  2050
Index 337  1010
Index 338  4192
Index 339  65472
Index 340  112
Index 341  65474
Index 342  4992
Index 343  62368
Index 344  2114
Index 345  64560
Index 346  7232
Index 347  62464
Index 348  2048
Index 349  0
Index 350  7026
Index 351  61520
Index 352  3922
Index 353  62576
Index 354  60494
Index 355  992
Index 356  64706
Index 357  64496
Index 358  61550
Index 359  1184
Index 360  64434
Index 361  65488
Index 362  62478
Index 363  80
Index 364  62498
Index 365  62544
Index 366  59356
Index 367  5008
Index 368  34
Index 369  61488
Index 370  58510
Index 371  4080
Index 372  64644
Index 373  62432
Index 374  61358
Index 375  992
Index 376  1108
Index 377  0
Index 378  63598
Index 379  2098
Index 380  1090
Index 381  64432
Index 382  63392
Index 383  128
Index 384  6146
Index 385  4178
Index 386  6256
Index 387  974
Index 388  5248
Index 389  4128
Index 390  6478
Index 391  64624
Index 392  2992
Index 393  2128
Index 394  7246
Index 395  62606
Index 396  48
Index 397  2050
Index 398  5008
Index 399  1022
Index 400  2144
Index 401  16
Index 402  3200
Index 403  63680
Index 404  1152
Index 405  0
Index 406  5104
Index 407  60528
Index 408  1170
Index 409  2
Index 410  4350
Index 411  62528
Index 412  64674
Index 413  64544
Index 414  4112
Index 415  61552
Index 416  66
Index 417  62608
Index 418  58526
Index 419  65520
Index 420  178
Index 421  61520
Index 422  58718
Index 423  224
Index 424  64450
Index 425  61552
Index 426  60526
Index 427  62656
Index 428  62546
Index 429  62512
Index 430  59326
Index 431  1040
Index 432  64642
Index 433  0
Index 434  57502
Index 435  208
Index 436  63650
Index 437  59488
Index 438  58398
Index 439  62624
Index 440  164
Index 441  61472
Index 442  60686
Index 443  112
Index 444  63698
Index 445  61520
Index 446  60496
Index 447  64688
Index 448  832
Index 449  3026
Index 450  2128
Index 451  63376
Index 452  992
Index 453  3890
Index 454  6048
Index 455  61520
Index 456  63232
Index 457  1954
Index 458  7056
Index 459  61408
Index 460  63280
Index 461  880
Index 462  0
Index 463  64254
Index 464  65424
Index 465  65362
Index 466  2000
Index 467  63392
Index 468  64384
Index 469  65218
Index 470  928
Index 471  60224
Index 472  65442
Index 473  65296
Index 474  6080
Index 475  61408
Index 476  64510
Index 477  64322
Index 478  4864
Index 479  61360
Index 480  3938
Index 481  2
Index 482  60542
Index 483  4032
Index 484  3058
Index 485  2896
Index 486  65486
Index 487  3200
Index 488  1810
Index 489  1984
Index 490  0
Index 491  3072
Index 492  1842
Index 493  2944
Index 494  62318
Index 495  7968
Index 496  4018
Index 497  1904
Index 498  63486
Index 499  7104
Index 500  4066
Index 501  1760
Index 502  63422
Index 503  4960
Index 504  6100
Index 505  2880
Index 506  3038
Index 507  7152
Index 508  4098
Index 509  3904
Index 510  2862
Index 511  6096
Index 512  63488
Index 513  1250
Index 514  270
Index 515  60544
Index 516  62704
Index 517  1074
Index 518  0
Index 519  61600
Index 520  60448
Index 521  98
Index 522  4160
Index 523  60432
Index 524  60448
Index 525  2
Index 526  992
Index 527  61536
Index 528  63506
Index 529  65442
Index 530  112
Index 531  59648
Index 532  62578
Index 533  61538
Index 534  64576
Index 535  58382
Index 536  63586
Index 537  63490
Index 538  2288
Index 539  59568
Index 540  61618
Index 541  63506
Index 542  1056
Index 543  58608
Index 544  64530
Index 545  62704
Index 546  0
Index 547  64672
Index 548  64754
Index 549  64594
Index 550  60686
Index 551  2240
Index 552  61506
Index 553  64608
Index 554  62558
Index 555  1040
Index 556  63522
Index 557  64544
Index 558  59390
Index 559  3184
Index 560  1058
Index 561  65472
Index 562  59534
Index 563  2320
Index 564  1138
Index 565  62592
Index 566  59456
Index 567  2080
Index 568  3188
Index 569  64576
Index 570  63728
Index 571  3264
Index 572  1234
Index 573  1042
Index 574  0
Index 575  2320
Index 576  64432
Index 577  34
Index 578  63648
Index 579  58384
Index 580  62560
Index 581  65490
Index 582  64622
Index 583  59424
Index 584  62226
Index 585  65394
Index 586  958
Index 587  59328
Index 588  61376
Index 589  64354
Index 590  62368
Index 591  61360
Index 592  63456
Index 593  61442
Index 594  62624
Index 595  60400
Index 596  60448
Index 597  61378
Index 598  64448
Index 599  58208
Index 600  59520
Index 601  62386
Index 602  0
Index 603  58416
Index 604  59440
Index 605  60450
Index 606  63472
Index 607  57424
Index 608  63426
Index 609  60464
Index 610  53422
Index 611  62466
Index 612  61538
Index 613  62432
Index 614  56446
Index 615  64562
Index 616  63250
Index 617  62336
Index 618  59310
Index 619  63424
Index 620  62402
Index 621  63344
Index 622  56222
Index 623  960
Index 624  65522
Index 625  59424
Index 626  55438
Index 627  2
Index 628  63538
Index 629  61376
Index 630  57294
Index 631  0
Index 632  63620
Index 633  63424
Index 634  58654
Index 635  64576
Index 636  64562
Index 637  60464
Index 638  60398
Index 639  80
Index 640  64320
Index 641  4098
Index 642  1102
Index 643  64336
Index 644  62558
Index 645  5906
Index 646  6128
Index 647  65504
Index 648  62320
Index 649  3906
Index 650  7024
Index 651  64304
Index 652  64320
Index 653  4818
Index 654  3824
Index 655  1760
Index 656  1808
Index 657  2882
Index 658  2992
Index 659  0
Index 660  65456
Index 661  1826
Index 662  2880
Index 663  63280
Index 664  65504
Index 665  1922
Index 666  4144
Index 667  65424
Index 668  65392
Index 669  2882
Index 670  2960
Index 671  65424
Index 672  62514
Index 673  62704
Index 674  55598
Index 675  80
Index 676  60736
Index 677  2
Index 678  60638
Index 679  1250
Index 680  61538
Index 681  64562
Index 682  61550
Index 683  2114
Index 684  63538
Index 685  976
Index 686  60398
Index 687  0
Index 688  2066
Index 689  63536
Index 690  59582
Index 691  3296
Index 692  1186
Index 693  64544
Index 694  60494
Index 695  3152
Index 696  1234
Index 697  128
Index 698  63790
Index 699  5248
Index 700  3170
Index 701  2080
Index 702  62576
Index 703  6272
Index 704  60224
Index 705  3042
Index 706  63504
Index 707  62272
Index 708  60400
Index 709  1922
Index 710  64638
Index 711  60496
Index 712  58208
Index 713  882
Index 714  3008
Index 715  0
Index 716  59280
Index 717  65458
Index 718  64304
Index 719  63328
Index 720  62352
Index 721  64370
Index 722  65456
Index 723  62400
Index 724  63344
Index 725  63410
Index 726  64416
Index 727  59312
Index 728  60432
Index 729  65506
Index 730  1072
Index 731  62416
Index 732  62336
Index 733  832
Index 734  65360
Index 735  64336
Index 736  65314
Index 737  1968
Index 738  60398
Index 739  4896
Index 740  976
Index 741  1888
Index 742  60510
Index 743  0
Index 744  64336
Index 745  2928
Index 746  64446
Index 747  6960
Index 748  65410
Index 749  1952
Index 750  62238
Index 751  9040
Index 752  3968
Index 753  2928
Index 754  63406
Index 755  8112
Index 756  5970
Index 757  1952
Index 758  63390
Index 759  7072
Index 760  5090
Index 761  4032
Index 762  1024
Index 763  9136
Index 764  7010
Index 765  5904
Index 766  1838
Index 767  13120
Index 768  1872
Index 769  8114
Index 770  4048
Index 771  0
Index 772  1952
Index 773  7890
Index 774  3102
Index 775  64528
Index 776  65312
Index 777  7874
Index 778  6014
Index 779  64480
Index 780  65424
Index 781  6944
Index 782  2814
Index 783  2880
Index 784  1936
Index 785  5026
Index 786  3088
Index 787  2016
Index 788  1952
Index 789  4034
Index 790  4976
Index 791  816
Index 792  944
Index 793  6898
Index 794  4078
Index 795  912
Index 796  65374
Index 797  6928
Index 798  846
Index 799  0
Index 800  60208
Index 801  61344
Index 802  52174
Index 803  63296
Index 804  61312
Index 805  63184
Index 806  54254
Index 807  63504
Index 808  60178
Index 809  63184
Index 810  58254
Index 811  62448
Index 812  60304
Index 813  63312
Index 814  57086
Index 815  864
Index 816  63394
Index 817  62400
Index 818  55326
Index 819  3040
Index 820  65458
Index 821  62416
Index 822  58254
Index 823  2880
Index 824  65458
Index 825  65264
Index 826  60382
Index 827  0
Index 828  834
Index 829  65296
Index 830  60238
Index 831  5008

**Comment by slavysis** [comment]
It looks like you somehow deleted some EERPOM cells - every 28th cell is erased. Here is the original content for this device:


00C2
799F
0000
2061
0005
0320
03E0
092A
B6F2
0189
0499
0000
1901
0000
0000
BE33
4320
FFB9
0101
0101
0101
F1F1
E0F1
CFD0
0000
0001
0002
F102
F102
F102
E0F2
C0E1
8995
3A02
EEDC
100F
1111
1122
0111
FF00
EDCC
000F
2222
3333
2233
1122
EE00
ABDD
1835
2FA9
2157
A581
7656
F9C4
3635
3331
2452
0C79
17B3
0625
F600
9797
9797
2AFA
23C0
10D0
20CE
07CE
1480
17A0
286E
FCBE
043E
13F0
28AE
FC4E
00AE
0850
14AE
043E
1080
0450
189E
FCCE
04BE
03A0
0CCE
F7BE
0860
F830
18A0
F04E
002E
F7E0
17C2
F3F0
2722
0C30
FC1C
1F10
17E0
12F0
07CC
1820
0790
0F5E
040C
17A0
0010
0BB0
F40E
1FA0
1BF4
07D0
FFFE
1430
0C32
0300
F03C
1350
13D2
FF90
041E
13C0
0FA2
FF40
FF4E
1380
1F20
17D0
1C4E
034E
087E
0FB0
205E
FC4E
0B20
1390
2F80
FFEE
07F0
0820
17DE
000E
1022
03F0
183E
F86E
0490
FC00
17E0
F370
0850
FFB0
1C50
F7DE
0BB0
FF40
1B80
F3D0
2382
0C40
FC9C
1BA0
0CC0
0C10
00CC
14A0
0F82
0FF0
0FDE
1440
0852
0470
F82E
1850
1464
0440
FC8E
14C0
08E2
FC60
F84E
13E0
0CC2
0020
04BE
1050
1012
03B0
FC0E
0C50
23B0
1410
205E
077E
1860
1790
20CE
FCAE
13C0
1000
245E
F86E
0C20
08A0
1B90
FC9E
1BE2
0440
112E
FCAE
0C52
F890
1460
F7F0
0882
0002
1CA0
F42E
0460
03C0
1BB0
F400
1F02
0B70
FBBE
12D0
13D0
0ED0
FC1C
1010
0F22
0B60
078E
0FA0
0F62
03E0
FAEE
17D0
1B24
FF80
F06E
17E0
1394
FBD0
F7AE
0F50
0FF2
0360
000E
1380
0BC2
0330
FF0E
0F70
13E0
1092
1C8E
03E0
08DE
17C0
24AE
FD2E
07E0
0C40
24AE
F84E
0BE0
0862
17F0
07DE
0C22
0050
10F0
F8A0
0842
FC20
1050
EC70
04E0
0010
2070
F440
0810
07A0
1BE0
F440
0B32
FFD0
F3DE
0B30
0020
0710
FBCE
0860
0312
FF80
FBEE
0B80
0322
FFA0
EF2E
1B00
0F44
FB80
EC2E
0FD0
0B74
F750
EF8E
07B0
0432
0340
03CE
0BA0
0F42
02E0
FB2E
0BA0
1730
1030
1C00
FF90
0890
13C0
2030
FC50
0390
0FA2
23EE
F43E
03F0
0822
13C0
036E
0802
03F2
1060
FFC0
0070
FFC2
1380
F3A0
0842
FC30
1C40
F400
0800
0372
1B72
F050
0F52
F470
EC4E
03E0
FCC2
FBF0
F06E
04A0
FBB2
FFD0
F40E
0050
F422
F450
E7DC
1390
0022
F030
E48E
0FF0
FC84
F3E0
EFAE
03E0
0454
F450
F86E
0832
0442
FBB0
F7A0
0080
1802
1052
1870
03CE
1480
1020
194E
FC70
0BB0
0850
1C4E
F48E
0030
0802
1390
03FE
0860
0010
0C80
F8C0
0480
F840
13F0
EC70
0492
0002
10FE
F440
FCA2
FC20
1010
F070
0042
F490
E49E
FFF0
00B2
F050
E55E
00E0
FBC2
F070
EC6E
F4C0
F452
F430
E7BE
0410
FC82
F030
E09E
00D0
F8A2
E860
E41E
F4A0
00A4
F020
ED0E
0070
F8D2
F050
EC50
FCB0
0340
0BD2
0850
F790
03E0
0F32
17A0
F050
F700
07A2
1B90
EFE0
F730
0370
0730
FAFE
FF90
FF52
07D0
F7A0
FB80
FEC2
03A0
EB40
FFA2
FF10
17C0
EFE0
FBFE
FB42
1300
EFB0
0F62
0002
EC7E
0FC0
0BF2
0B50
FFCE
0C80
0712
07C0
03BE
0C00
0732
0B80
F36E
1F20
0FB2
0770
F7FE
1BC0
0FE2
06E0
F7BE
1360
17D4
0B40
0BDE
1BF0
1002
0F40
0B2E
17D0
F800
04E2
010E
EC80
F4F0
0432
08FE
F0A0
EC20
0062
1040
EC10
EC20
0002
03E0
F060
F812
FFA2
0070
E900
F472
F062
FC40
E40E
F862
F802
08F0
E8B0
F0B2
F812
0420
E4F0
FC12
F4F0
E11E
FCA0
FCF2
FC52
ED0E
08C0
F042
FC60
F45E
0410
F822
FC20
E7FE
0C70
0422
FFC0
E88E
0910
0472
F480
E840
0820
0C74
FC40
F8F0
0CC0
04D2
0412
F820
0910
FBB0
0022
F8A0
E410
F460
FFD2
FC6E
E820
F312
FF72
03BE
E7C0
EFC0
FB62
F3A0
EFB0
F7E0
F002
F4A0
EBF0
EC20
EFC2
FBC0
E360
E880
F3B2
F51E
E430
E830
EC22
F7F0
E050
F7C2
EC30
D0AE
F402
F062
F3E0
DC7E
FC32
F712
F380
E7AE
F7C0
F3C2
F770
DB9E
03C0
FFF2
E820
D88E
0002
F832
EFC0
DFCE
FF90
F884
F7C0
E51E
FC40
FC32
EC30
EBEE
0050
FB40
1002
044E
FB50
F45E
1712
17F0
FFE0
F370
0F42
1B70
FB30
FB40
12D2
0EF0
06E0
0710
0B42
0BB0
FBE0
FFB0
0722
0B40
F730
FFE0
0782
1030
FF90
FF70
0B42
0B90
FF90
F432
F4F0
D92E
0050
ED40
0002
ECDE
04E2
F062
FC32
F06E
0842
F832
03D0
EBEE
1BF0
0812
F830
E8BE
0CE0
04A2
FC20
EC4E
0C50
04D2
0080
F92E
1480
0C62
0820
F470
1880
EB40
0BE2
F810
F340
EBF0
0782
FC7E
EC50
E360
0372
0BC0
EF80
E790
FFB2
FB30
F760
F390
FB72
FFB0
F3C0
F770
F7B2
FBA0
E7B0
EC10
FFE2
0430
F3D0
F380
0340
FF50
FB50
FF22
07B0
EBEE
1320
03D0
0760
EC5E
0C40
FB50
0B70
FBBE
1B30
FF82
07A0
F31E
2350
0F80
0B70
F7AE
1FB0
1752
07A0
F79E
1BA0
13E2
0FC0
0400
23B0
1B62
1710
072E
3340
0750
1FB2
0FD0
0350
07A0
1ED2
0C1E
FC10
FF20
1EC2
177E
FBE0
FF90
1B20
0AFE
0B40
0790
13A2
0C10
07E0
07A0
0FC2
1370
0330
03B0
1AF2
0FEE
0390
FF5E
1B10
034E
0F80
EB30
EFA0
CBCE
F740
EF80
F6D0
D3EE
F810
EB12
F6D0
E38E
F3F0
EB90
F750
DEFE
0360
F7A2
F3C0
D81E
0BE0
FFB2
F3D0
E38E
0B40
FFB2
FEF0
EBDE
0780
0342
FF10
EB4E
1390
