### ISSUE TITLE
eeprom validation

### ISSUE THREAD

**Issue by AsdyCorp** [melexis/mlx90640-library#109]
I'm working with mlx90640 for about week and I'm getting image but it's too noisy and I always get Parameter extraction failed. I think my eeprom corrupted after all these days. 
Based on
https://github.com/melexis/mlx90640-library/issues/107#issuecomment-1623728833
I assume malexis have database of eeprom factory dumps ( or it's possible to recalculate them based on other eeprom data). Is it possible to somehow get factory dump for my device or get access to archive of all dumps?
My current dump:
`
Serial number: 13049C4718B
0x00b4
,0x899f
,0x0000
,0x2061
,0x0005
,0x0320
,0x03e0
,0x1304
,0x9c47
,0x018b
,0x0499
,0x0000
,0xffff
,0x0000
,0x0000
,0xbe33
,0x4320
,0xffc0
,0x0101
,0x0101
,0x0101
,0xf101
,0xe0f1
,0xc0e0
,0x0112
,0x0112
,0xf102
,0xf102
,0xf103
,0xe0f2
,0xd0e2
,0xb0e1
,0x8895
,0x38de
,0xffff
,0x110f
,0x3322
,0x2233
,0x0011
,0xccee
,0xdcbb
,0x0ffe
,0x2111
,0x2232
,0x2233
,0x1122
,0xf011
,0xddef
,0x169e
,0x2fb0
,0x2155
,0xa27b
,0x6555
,0xf184
,0x6261
,0x5e5d
,0x2463
,0xffff
,0x0000
,0x0000
,0xf600
,0xc5cc
,0x97b1
,0x2669
,0x0fbe
,0x0bfe
,0x1c2e
,0x077e
,0x13de
,0x074e
,0x23fe
,0xff3e
,0x0f9e
,0x0800
,0x1c5e
,0x077e
,0x083e
,0x07ae
,0xffff
,0xfc7e
,0x03a0
,0xffb0
,0x144e
,0xf41e
,0x0430
,0x07e0
,0x1860
,0xf470
,0x0002
,0x07c0
,0x1750
,0xfc10
,0xfb90
,0xf412
,0x0fd0
,0xfb70
,0x1002
,0x085e
,0x008c
,0x1fce
,0x1430
,0xffff
,0x045c
,0x1b80
,0x1000
,0x0c5e
,0x00bc
,0x23b0
,0x0ca0
,0x07fe
,0x008c
,0x14b0
,0x0402
,0x03fe
,0xfcae
,0x1040
,0x0c72
,0x083e
,0x04be
,0x14c0
,0x0864
,0x0c10
,0x07ae
,0xffff
,0x0bf0
,0x0060
,0xf83e
,0x1bc0
,0x07ee
,0x046e
,0x1c4e
,0x03ae
,0x0c50
,0x03c0
,0x1c9e
,0xfbde
,0x0fee
,0x0830
,0x1c5e
,0x07fe
,0x086e
,0x0050
,0x14b0
,0xf8be
,0xfc00
,0xf800
,0xffff
,0xf450
,0x0840
,0x0070
,0x1c2e
,0xfff0
,0x0412
,0x07d0
,0x1790
,0xfca0
,0x03d0
,0xf4b0
,0x13f0
,0xff80
,0x0fb0
,0x043e
,0x002c
,0x1b70
,0x1022
,0x078e
,0x007c
,0xffff
,0x13c2
,0x0ffe
,0x043e
,0x1fc0
,0x1022
,0x002e
,0xfc8c
,0x1470
,0x07d2
,0x03de
,0xfc4e
,0x1020
,0x1022
,0x0840
,0x0bfe
,0x1bb0
,0x0fe2
,0x1390
,0x076e
,0x1862
,0x0ba2
,0xffff
,0xfbee
,0x1f50
,0x0fce
,0x0450
,0x184c
,0x03cc
,0x1800
,0x07d0
,0x1c7e
,0xffde
,0x17b0
,0x0c60
,0x188e
,0x07de
,0x105e
,0x07e0
,0x1480
,0x004e
,0x0792
,0xfc00
,0x1070
,0xfbde
,0xffff
,0x0430
,0x1c90
,0xf870
,0x0462
,0x0be0
,0x17a0
,0x0050
,0xffe0
,0xf8a2
,0x1782
,0xffa0
,0x0f90
,0x001e
,0xfc2c
,0x1390
,0x1be2
,0x03ae
,0x004e
,0x1790
,0x1b82
,0xffff
,0xfc6c
,0x1b8e
,0x1012
,0x0790
,0xfc5e
,0x17e0
,0x0b52
,0x03c0
,0xf84e
,0x1390
,0x0c62
,0x0bf0
,0x045e
,0x1430
,0x0834
,0x0f90
,0x036e
,0x1810
,0x07c2
,0x0060
,0xff6e
,0x1b50
,0xffff
,0x0040
,0x1fde
,0x03de
,0x087e
,0x07a0
,0x1c10
,0xffde
,0x0fd0
,0x0fd0
,0x1ff0
,0x07be
,0x0c00
,0x07c0
,0x1430
,0xfcae
,0xf810
,0xffe0
,0x0c90
,0xf40e
,0x0452
,0x0410
,0xffff
,0xf85e
,0x07e0
,0x07f2
,0x1780
,0xfc40
,0x03a2
,0xf4b0
,0x1752
,0xff60
,0x07d0
,0xf87e
,0xfc1e
,0x0c0e
,0x04b2
,0xffde
,0xfc5e
,0x0c00
,0x0c22
,0x0800
,0xfc3e
,0x1be0
,0xffff
,0x03e0
,0xf47e
,0x10d0
,0xf852
,0xf810
,0xf0de
,0x0c30
,0x0492
,0x0440
,0x043e
,0x1090
,0x0832
,0x0820
,0xfbde
,0x1470
,0x07d2
,0xf8e0
,0xfb9e
,0x1792
,0x0b50
,0x07e0
,0xffff
,0xffae
,0x0870
,0x0780
,0x1870
,0xf81e
,0x0bf0
,0x0840
,0x1440
,0x0760
,0x0480
,0x0790
,0x1080
,0xf89e
,0xff72
,0xffb0
,0x1040
,0xf440
,0x0060
,0x0440
,0x1c20
,0xf830
,0xffff
,0x0bb0
,0x1772
,0xfc50
,0xffb2
,0xf882
,0x0fd0
,0xfbd0
,0x0382
,0xf41e
,0xec9e
,0x0bc0
,0x00b2
,0xf7b0
,0xf4ae
,0x0430
,0x0422
,0x0060
,0xf48e
,0x1780
,0x00c2
,0xffb0
,0xffff
,0x0ca0
,0xffc2
,0xfbd0
,0xf07e
,0x0460
,0x0092
,0x0080
,0xfc50
,0x0c60
,0x0bc4
,0x07f0
,0xf7c0
,0x1090
,0x03e4
,0xf4b0
,0xf000
,0x0c00
,0x0f00
,0x07d0
,0x17e0
,0xff80
,0xffff
,0x0380
,0x146e
,0xff2e
,0x0f90
,0x0be2
,0x1010
,0x034e
,0x0fb2
,0x0720
,0x0c3e
,0xf85e
,0xf800
,0xff90
,0x0c20
,0xf010
,0x0410
,0x0412
,0x1430
,0xf800
,0xffc2
,0x07b0
,0x0b52
,0xffff
,0xf7a2
,0xf462
,0x0780
,0xf790
,0x0332
,0xefee
,0xe81e
,0x0390
,0x07f2
,0xf3a0
,0xe89e
,0x0730
,0x07d2
,0xfbf0
,0xec4e
,0x0b60
,0x07e2
,0xf75e
,0xe86e
,0x0460
,0xf042
,0xffff
,0xe86e
,0x0030
,0x0044
,0xf830
,0xf46e
,0x0822
,0xffe4
,0xffc0
,0xf390
,0x0c20
,0xf7d2
,0xec80
,0xefa0
,0x0ba0
,0xf790
,0xfc30
,0x082e
,0xf7c0
,0x0002
,0xffc0
,0xffff
,0xf3f0
,0x03a0
,0x0430
,0x0c20
,0xff60
,0x0010
,0xffb0
,0x0822
,0xf440
,0xf772
,0xf7e0
,0x0460
,0xec4e
,0xfc12
,0xfc92
,0x1020
,0xf050
,0xff92
,0x0012
,0x0f52
,0xf830
,0xf762
,0xffff
,0x0770
,0xf3a0
,0xf322
,0xe02e
,0xdc3e
,0xf7d0
,0xf412
,0xe7e0
,0xe41e
,0xf7f0
,0xf7d2
,0xf04e
,0xe04e
,0x0780
,0xf432
,0xefc0
,0xe04e
,0xfc50
,0xefa4
,0xe410
,0xdc8e
,0xffff
,0xf442
,0xecb0
,0xec6e
,0x0060
,0xfbb4
,0xf420
,0xeb70
,0x0442
,0xf792
,0xe870
,0xe790
,0x03b0
,0xefb0
,0xfc12
,0x0420
,0xf770
,0xf840
,0xf810
,0x04c0
,0xeff0
,0xffd2
,0xffff
,0x0490
,0xfb70
,0xf840
,0xff92
,0x0050
,0xf050
,0xefc0
,0xf072
,0x0062
,0xe840
,0xf0b0
,0xfc62
,0x08c0
,0xf020
,0xf412
,0xfc02
,0x0782
,0xf0c0
,0xefe0
,0xf092
,0xfc00
,0xffff
,0xffc2
,0xf810
,0xf03e
,0x1370
,0x0862
,0xf810
,0xf4de
,0x0c00
,0x0fe2
,0x04b0
,0xf4ce
,0x1b80
,0x0862
,0x07a0
,0xf47e
,0x1460
,0x07d2
,0xf870
,0xf47e
,0x1050
,0x08c2
,0x0c30
,0xffff
,0x1822
,0x0c34
,0x1010
,0x039e
,0x1cc2
,0x0bf2
,0x04a0
,0xf800
,0x1f92
,0xf772
,0xf802
,0xfc40
,0xf3a0
,0xf830
,0xf000
,0xf8b0
,0xeb90
,0xfbb0
,0xf890
,0xf840
,0xf3e0
,0xffff
,0xf7a2
,0xf840
,0xec90
,0xefb0
,0xe870
,0xf4f0
,0xe090
,0xf442
,0xf4c0
,0x00b0
,0xec10
,0xe460
,0xf442
,0xf7c0
,0xe8f0
,0xe3f0
,0xe8e2
,0xeff0
,0xef90
,0xfb84
,0xf000
,0xffff
,0x0792
,0xfc32
,0xeff0
,0xe4be
,0x0790
,0x07d2
,0xf890
,0xec6e
,0x0be0
,0x0092
,0xfba0
,0xec6e
,0x0490
,0xffb4
,0xf070
,0xe51e
,0x0482
,0x0462
,0x00c0
,0xf4ce
,0x1422
,0xffff
,0x0030
,0xf3ce
,0x08f0
,0xfc02
,0xf4e0
,0xefe0
,0x1382
,0xf3e0
,0x0842
,0x0c30
,0x03b0
,0x0030
,0x0bc2
,0x0c80
,0xfc10
,0x0bb2
,0x1062
,0x10b0
,0x0400
,0x00b0
,0x0fa0
,0xffff
,0x0440
,0xff82
,0x0442
,0x0c90
,0xfc30
,0x0450
,0x0cb2
,0x1890
,0x0430
,0x07f2
,0x1002
,0x13c0
,0x0470
,0xffb2
,0x0452
,0x0f72
,0x0790
,0xf3d2
,0xf830
,0xec3e
,0x1390
,0xffff
,0xff90
,0xf47e
,0x13e0
,0x13b2
,0x0c40
,0xf4be
,0x1ff0
,0x08b2
,0x0fa0
,0xfc6e
,0x1c40
,0x0b92
,0x0440
,0xf4a0
,0x1822
,0x1062
,0x10a0
,0x04ae
,0x2422
,0x1404
,0x1bf0
,0xffff
,0x2862
,0x13a2
,0x0c30
,0x037e
,0x2b70
,0xe7b0
,0x0432
,0xfc40
,0xfbc0
,0xf040
,0x0362
,0x0440
,0xf000
,0xfbe0
,0x04a0
,0x0850
,0xf860
,0xf4c0
,0x03e2
,0x00c0
,0xf4d0
,0xf3c2
,0xffff
,0x0460
,0xf0a0
,0xf872
,0x04d2
,0x0ca0
,0xf4e0
,0xffe2
,0x0c12
,0x0002
,0xf8b0
,0xefb0
,0xfc90
,0xfbd0
,0xff90
,0xe3a2
,0xe810
,0xdc20
,0xff90
,0xf032
,0xf340
,0xe44e
,0xffff
,0xfbe2
,0xf870
,0xe85e
,0x0850
,0xf8c2
,0xfbe0
,0xe4ce
,0x08c2
,0xf7e2
,0xfbc0
,0xe88e
,0x0890
,0x0082
,0xfcc0
,0xf0be
,0x0ce0
,0x0bd4
,0x0bf2
,0xefee
,0x1890
,0x0372
,0xfc70
,0xffff
,0x1f62
,0xdbf0
,0xf462
,0xf000
,0xf320
,0xe800
,0xf772
,0xf7f0
,0xeb50
,0xebd0
,0xffd2
,0xec60
,0xefd0
,0xec70
,0xff30
,0xec9e
,0xe890
,0xe7f0
,0xf000
,0xf470
,0xe860
,0xffff
,0xfc82
,0x0062
,0xec90
,0xdc20
,0xfc10
,0xeba0
,0xec60
,0xdf60
,0xf800
,0xe750
,0xfb30
,0xeff2
,0xf450
,0xe7f0
,0x1320
,0x0002
,0xfb70
,0xec0e
,0x1330
,0x07d2
,0xffff
,0xf05e
,0x13c0
,0x0c72
,0x0f20
,0xf09e
,0x1492
,0x0412
,0x0800
,0xf49e
,0x1872
,0x10a2
,0x1480
,0x0480
,0x2082
,0x0832
,0x1400
,0xfbbe
,0x1c50
,0x0f52
,0x17f0
,0x034e
,0x3320
`

**Comment by LBuydens** [comment]
Yes, the EEPROM is corrupted.  See attached file for factory settings
[EEPROM_recover.xlsx](https://github.com/melexis/mlx90640-library/files/12891847/EEPROM_recover.xlsx)
