### ISSUE TITLE
How interpreting data from MLX90640_GetImage ?

### ISSUE THREAD

**Issue by AsdyCorp** [melexis/mlx90640-library#110]
If CalculateTo gives us float values of object temperature in celisus of "pixels" how to interpreting data from GetImage ? what are ranges and what they mean?

**Comment by LBuydens** [comment]
The values obtained from GetImage indicate only if something is hot(ter) or cold(er). Positive values are hotter than the sensor, negative are colder. But this is not calibrated and not a linear scale.

**Comment by AsdyCorp** [comment]
> The values obtained from GetImage indicate only if something is hot(ter) or cold(er). Positive values are hotter than the sensor, negative are colder. But this is not calibrated and not a linear scale.

So we can compare them to Ta ? and theoretically - if we put dry ice or some other cold agent near sensor it must improve it sensitivity, especially in GetImage  function?

**Comment by LBuydens** [comment]
It's relative to Ta. You will not gain that much by cooling.

**Comment by AsdyCorp** [comment]
> It's relative to Ta. You will not gain that much by cooling.

but with coolling all values from GetImage should be positive then, right?

**Comment by LBuydens** [comment]
Yes, but if that's the goal, better just add enough.

**Comment by AsdyCorp** [comment]
thanks
