### ISSUE TITLE
Defective pixels processing

### ISSUE THREAD

**Issue by GeorgeZheng2018** [melexis/mlx90640-library#14]
Hi  @slavysis  

Thanks for your excellent library, which is very helpful for me to test and understand the sensor.

In current library, it is only identifying the defective pixels from the EEPROM datas and checking their adjacent pixels. Do you have the plan to add the defective pixels processing in the library?

I remember  you mentioned that max I2C clock freq.  is 400KHz for reading Mlx90640's EEPROM info. and 1MHz for reading RAM info. It is not found in MLX90640's specification. Why does it need to limit
the communication rate for EEPROM reading? 

Thanks.

**Comment by slavysis** [comment]
I am planning to add defective pixels processing, but I cannot tell when it will be available.
The limitation is required to guarantee stable readings from the EEPROM. Thanks for the 
specification tip.

Best regards

**Comment by cimba007** [comment]
I also have a defective pixel. Keep the good work on this excellent library up @slavysis  ;-)

**Comment by slavysis** [comment]
There is already a function for correcting the defective pixels.

Best regards
