### ISSUE TITLE
limited range on datatypes

### ISSUE THREAD

**Issue by Kiogora** [melexis/mlx90640-library#16]
I received  these compiler warnings while using the esp-idf toolchain to perform the tests.

```
In function 'ExtractGainParameters':
mlx90640_api.c:613:15: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if(gainEE > 32767)
               ^

mlx90640_api.c:785:19: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (offsetRef > 32767)
                   ^

mlx90640_api.c: In function 'ExtractKtaPixelParameters':
mlx90640_api.c:855:17: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (KtaRoCo > 127)
```
Are the limited ranges of the datatypes used intended? I haven't yet analyzed the effect of this with reference to the datasheet but I thought I may raise it here first.

**Comment by Kiogora** [comment]
Just checked the code cleanly and I notice these are sanity checks in case of overflow issues on the data passed. I shall now close this issue.

**Comment by sagar448** [comment]
@Kiogora Hey I know this is very long time ago but did you manage to run the MLX90640 on the esp32 esp-idf? If so do you have the code for it? It would really help!

**Comment by Kiogora** [comment]
Check https://github.com/Kaiote-opensource/OpenHAP/tree/master/firmware/components/drivers_thermal_imagers
