### ISSUE TITLE
Synchronizing two sensors

### ISSUE THREAD

**Issue by kozuch** [melexis/mlx90640-library#17]
Is it possible to frame-synchronize two MLX90640 sensors so that they take a reading (image) exactly at the same time? Is it possible to have a synchronized "video stream" from two sensors where the individual frames are in sync?

**Comment by slavysis** [comment]
I am afraid you can not truly sync the sensors.

Best regards

**Comment by kozuch** [comment]
Is the refresh rate of a single sensor at least relatively stable through time?
