### ISSUE TITLE
Possible bug (and compilation error on some C++ compilers)

### ISSUE THREAD

**Issue by lucaong** [melexis/mlx90640-library#18]
The `MLX90640_BadPixelsCorrection` function uses `abs` on this line:

https://github.com/melexis/mlx90640-library/blob/master/functions/MLX90640_API.cpp#L634

Unfortunately, depending on the C++ compiler, including `math.h` and using `abs` can lead to different results: some compilers would use the `float abs(float)` version, some the `int abs(int)`, some would just not declare `abs` and lead to compilation errors.

Example: https://wandbox.org/permlink/CaEOR8V3iQJSbyjt (try changing the `gcc` version on the top left, for example to `5.x.y`)

A safe alternative is to use `fabs` instead.

**Comment by slavysis** [comment]
Thanks for the remark! I fixed it.

Best regards

**Comment by lucaong** [comment]
You're welcome, and thanks for the great work!
