### ISSUE TITLE
Info Request

### ISSUE THREAD

**Issue by adibacco** [melexis/mlx90640-library#30]
Is it possible to recognize the FOV (55 or 110) from the dev_id1, dev_id2, dev_id3 ?

**Comment by slavysis** [comment]
The dev_id does not include such information. There is still a way to recognize the FOV of the device base on the EEPROM values. You need to decode the value of bits[3:2] at EEPROM address 0x240A (mask the EEPROM value with 0x000C). If the bits are b'10 then you have a 55deg FOV and if the bits are b'11, the device has 110deg FOV
