### ISSUE TITLE
What is the relationship between temperature and distance in MLX90640?

### ISSUE THREAD

**Issue by imliubo** [melexis/mlx90640-library#40]
Hi:
    When I tested, I found that the measured object was far away from the sensor, and the temperature dropped a lot. So I was wondering if there is any way to make the data correct.
Change emissivity or sensitivity? I don't know how to set it up.What is the maximum measurement distance of the MLX90640 (the distance of the sensor from the measured object)?

Have a nice day!
IAMLIUBO

**Comment by Ritesh236** [comment]
Hello,

I have one relevant question like how to calculate object distance as per FOV provided? 

Regards,
Ritesh Prajapati
