### ISSUE TITLE
warning: unused variable 'vdd'

### ISSUE THREAD

**Issue by h-Naima-s** [melexis/mlx90640-library#41]
I am using MLX90640 evaluation board (https://www.melexis.com/en/product/EVB90640-41/Evaluation-Board-MLX90640-41) and Teensy 3.2. I have connected SCL of sensor to Pin 19 of Teensy and SDA to Pin 18. Teensy 3.2 I have powered by connecting it to my computer. VDD and GND of sensor are connected to 3.3V (Pin 24) and AGND (Pin 25) on Teensy respectively. When I am uploading this code (https://github.com/sparkfun/SparkFun_MLX90640_Arduino_Example/tree/master/Firmware/Example1_BasicReadings), I am getting following error and the code is not working.

In function 'void loop()':
55: warning: unused variable 'vdd'
float vdd = MLX90640_GetVdd(mlx90640Frame, &mlx90640);

What is wrong here? something with code or pin connections I made. Please guide.

**Comment by slavysis** [comment]
Hello,

What are you trying to achieve? The MLX90640 EVB is sufficient to handle the MLX90640 communication and calculations. Why would you connect Teensy to it?

> I am getting following error and the code is not working.
> 
> In function 'void loop()':
> 55: warning: unused variable 'vdd'
> float vdd = MLX90640_GetVdd(mlx90640Frame, &mlx90640);

This is not an error, but a warning and should not cause any issues. Most likely the compiler
will simply disregard this piece of code, which is not needed anyways.

Best regards
