### ISSUE TITLE
Fix PDF documentation 

### ISSUE THREAD

**Issue by garciaolais** [melexis/mlx90640-library#49]
Hi

Please change ✍️  `MLX90640_GetResolution`  -> `MLX90640_GetCurResolution` 

Page 7
![BadFoo](https://user-images.githubusercontent.com/14133711/69304466-51253d00-0be6-11ea-8904-8d37d3314074.jpg)

**Comment by slavysis** [comment]
Thanks for noticing. It is fixed and the new pdf file is uploaded

Best regards
