### ISSUE TITLE
RuntimeError("Too many retries")

### ISSUE THREAD

**Issue by matiasandina** [melexis/mlx90640-library#57]
I have been using this camera for an application at 32 Hz. It works fine, however, I get `RuntimeError("Too many retries")` quite often (camera can't run for 5 minutes straight).
Any advice on how to catch this error and restart the camera or any chance you can increase the `cnt` value in `_GetFrameData`?

**Comment by slavysis** [comment]
The GetFrameData function returns -8 when valid data can not be acquired for 5 'frames'. This could help you to 'catch' the error and deal with it. If you want to, you could simply call the function until you get valid data. Be careful though to not create an endless loop and hang the MCU. The reason for getting this error is that the I2C read-out time is too much compared to the refresh rate of the sensor. Even if the cnt is increased you are still dropping frames.

Best regards

**Comment by slavysis** [comment]
New version uploaded with no multiple retries.

Best regards
