### ISSUE TITLE
Possible overflow when rescaling alpha / kv / kta

### ISSUE THREAD

**Issue by jamesl-dm** [melexis/mlx90640-library#60]
After the alpha / kv / kta values are read from eeprom and calculated as floating point values, they are rescaled and saved as integers in the parameter array.

It looks like the rescaling code can overflow on the positive side. For instance in ExtractKtaPixelParameters, temp is assigned the maximum fabs() of all values in ktaTemp, and then:

    ktaScale1 = 0;
    while(temp < 64)
    {
        temp = temp*2;
        ktaScale1 = ktaScale1 + 1;
    }    
     
    for(int i = 0; i < 768; i++)
    {
        temp = ktaTemp[i] * pow(2,(double)ktaScale1);
        if (temp < 0)
        {
            mlx90640->kta[i] = (temp - 0.5);
        }
        else
        {
            mlx90640->kta[i] = (temp + 0.5);
        }        
     }

If temp is 63.75 (or 63.75 / 2^n), ktaScale1 will be chosen to make the scaled maximum 127.5. Which will then round up to 128, and not fit in the int8_t container.

**Comment by slavysis** [comment]
Thanks a lot for that feedback! New version is uploaded, where that should be fixed.

Best regards
