### ISSUE TITLE
Query for MLX90640 and MLX90632 IR Thermal Sensors

### ISSUE THREAD

**Issue by Ritesh236** [melexis/mlx90640-library#62]
Hello Everypone,

Hope you are doing well and everyone is same at their end.

Actually, We are thinking to create IR Thermal Camera System and we felt to use Melexis Sensors for same.

We looked and found that either MLX90640 or MLX90632 can be used into our application.

But, I want to know much details from accuracy and measurement point of practical details which have been measured on those modules.

So, can anyone provide those kind of such details which will be beneficial for us to move further for same?

Regards,
Ritesh Prajapati

**Comment by slavysis** [comment]
Hi,

MLX90632 is a single pixel device, so this is not really suitable for  IR Thermal camera.
The accuracy for the devices is specified in the datasheets.

Best regards

**Comment by Ritesh236** [comment]
@slavysis ,

Thanks for your quick response.

So, Would you please suggest which one is best suitable module to use for IR Thermal Camera to measure non-contact body temperature?

Regards,
Ritesh Prajapati

**Comment by Ritesh236** [comment]
@slavysis ,

I have also check MLX90614 Data-sheet which is also for single pixel device nut mentioned to use it for Body temperature measurement. So, I am little bit confused as multiple pixel supported module is better to use then single pixel module.

Regards,
Ritesh Prajapati

**Comment by LBuydens** [comment]
Dear sir,

This channel is not monitored by Melexis for the questions you are asking.  
Please contact sales@melexis.com

Regards.
