### ISSUE TITLE
mlx90640 with Glass(for IP65 rating)

### ISSUE THREAD

**Issue by IXMSbhatt** [melexis/mlx90640-library#63]
Hi Support,
Face recognize product with thermal support we are using mlx90640. We want put transparent glass in front of camera lens to protect dust and humid. Is there any temperature impact with Glass?

www.invixium.com

**Comment by LBuydens** [comment]
The sensor cannot look through glass.  
You should use AR coated silicon or PE.  And you will even then have to adjust for the absorption in the window.  You better try to seal around the sensor.
