### ISSUE TITLE
mbed.h no such file in directory

### ISSUE THREAD

**Issue by Googlesmagic** [melexis/mlx90640-library#70]
I have been getting this error when trying to compile the code for an arduino duo. I am fairly new to this and I am not sure what I am doing wrong. I am not sure if I need to download the mbed,h file online somewhere as I am having trouble finding it.

Cheers

**Comment by slavysis** [comment]
Hi, the MLX90640_I2C_Driver.cpp should be modified for any specific MCU. The included file is an example for MBED. For more details, please refer to MLX90640 driver.pdf

Best regards

**Comment by kkaryono** [comment]
Hi, I am fairly new also, but I've managed to run the module. You can use the code which is already available like Adafruit code https://github.com/adafruit/Adafruit_MLX90640 or Spark Fun https://github.com/sparkfun/SparkFun_MLX90640_Arduino_Example.
Kind Regards,
